### ISSUE TITLE
Example web try to run but error

### ISSUE THREAD

**Issue by a0fzide** [robertknight/tesseract-wasm#43]
I follow instruction but I still cannot run it

https://github.com/robertknight/tesseract-wasm/tree/main/examples/web

import { cpSync } from "node:fs";
         ^^^^^^
SyntaxError: The requested module 'node:fs' does not provide an export named 'cpSync'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:121:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:166:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

**Comment by robertknight** [comment]
What version of Node do you have? (`node --version`). According to the [API history information](https://nodejs.org/api/fs.html#fscpsyncsrc-dest-options) this requires Node v16.7 or later.

**Comment by a0fzide** [comment]
I already update node version and run terminal as administrator to make it work.

Thank you very much.
