### ISSUE TITLE
Failed to reconfigize chinese text

### ISSUE THREAD

**Issue by shrinktofit** [robertknight/tesseract-wasm#65]
The trained data used is fetched from: https://github.com/tesseract-ocr/tessdata/blob/main/chi_sim.traineddata

The image:

<img width="139" alt="img" src="https://user-images.githubusercontent.com/28807867/184413687-30baad71-a37c-425a-b937-8a3a936ebd98.png">

The error:

```
## <Seems like compiled wasm glue code>
... eturn (Module["dynCall_jii"]=Module["asm"]["ma"]).apply(null,arguments)};var calledRun;dependenciesFulfilled=function runCaller(){if(!calledRun)run();if(!calledRun)dependenciesFulfilled=runCaller;};function run(args){if(runDependencies>0){return}preRun();if(runDependencies>0){return}function doRun(){if(calledRun)return;calledRun=true;Module["calledRun"]=true;if(ABORT)return;initRuntime();readyPromiseResolve(Module);if(Module["onRuntimeInitialized"])Module["onRuntimeInitialized"]();postRun();}if(Module["setStatus"]){Module["setStatus"]("Running...");setTimeout(function(){setTimeout(function(){Module["setStatus"]("");},1);doRun();},1);}else {doRun();}}Module["run"]=run;if(Module["preInit"]){if(typeof Modu
    at abort (file:///X:/Temp/auto-bb/node_modules/tesseract-wasm/dist/lib.js:539:7465)
    at _abort (file:///X:/Temp/auto-bb/node_modules/tesseract-wasm/dist/lib.js:539:54327)
    at wasm://wasm/0067125a:wasm-function[50]:0x1b74 
    at wasm://wasm/0067125a:wasm-function[694]:0x5d8d2
    at wasm://wasm/0067125a:wasm-function[872]:0x8434f
    at wasm://wasm/0067125a:wasm-function[1733]:0x14bb88
    at wasm://wasm/0067125a:wasm-function[1953]:0x16e2fb
    at OCREngine$loadModel [as loadModel] (eval at new_ (file:///X:/Temp/auto-bb/node_modules/tesseract-wasm/dist/lib.js:539:36290), <anonymous>:9:10)
    at OCREngine.loadModel (file:///X:/Temp/auto-bb/node_modules/tesseract-wasm/dist/lib.js:629:37)
    at main (file:///X:/Temp/auto-bb/index.mjs:24:12)
```

**Comment by shrinktofit** [comment]
I also tried https://github.com/tesseract-ocr/tessdata/blob/main/chi_sim_vert.traineddata . There was no error like above but the result is completely incorrect. But I guess this is due to the traned data itself.

**Comment by robertknight** [comment]
Is there any other output in the browser console near the error stack above? It looks like some internal assert is being tripped, in which case I'd expect to see a message about what caused the abort.
